# Generated by Django 4.2.5 on 2023-10-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='cpucooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='powersupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='videocard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.CharField(max_length=15)),
            ],
        ),
    ]
